AWSTemplateFormatVersion: '2010-09-09'
Description: "es-cleanup-app\nSAM Template for sam-app - ES Cleanup \n"
Globals:
  Function:
    Environment:
      Variables:
        EsHost: search-voodoo-prod-kzhnusnkwaszd7cmd3fcmgegte.eu-west-2.es.amazonaws.com
    Timeout: 15
Outputs:
  EsCleanupFunction:
    Description: ES Cleanup Lambda Function ARN
    Value:
      Fn::GetAtt:
      - EsCleanupFunction
      - Arn
Resources:
  EsCleanupFunction:
    Properties:
      CodeUri: s3://sam-bucket-escleanup-ldn-prod/849c7ef917ceb2c4c8b6ae94c1c607c6
      Handler: app.lambda_handler
      Runtime: python2.7
    Type: AWS::Serverless::Function
Transform: AWS::Serverless-2016-10-31
